### ISSUE TITLE
Please rename repo and organisation

### ISSUE THREAD

**Issue by ugermann** [uoe-infk8s-cluster-users/infk8s-cluster-users#31]
EIDF has asked us to make it clear that this is not official EIDF documentation. Other EIDF users have relied on information provided here, and this has caused problems for the EIDF cluster management.

I'd suggest renaming the organisation to uoe-infk8s-cluster-users and the repo to infk8s-cluster-users.

**Comment by AntreasAntoniou** [comment]
@pminervini Created both of these, so I'll let him make the changes

**Comment by ugermann** [comment]
Thanks, Antreas! Over to @pminervini ...

**Comment by pminervini** [comment]
> Thanks, Antreas! Over to @pminervini ...

Will do it shortly!

**Comment by pminervini** [comment]
Done!
